
title: Zach Caterer
description: Zach Caterer – PhD student at CU Boulder studying computational biology, genomics, and bioinformatics.
url: "https://caterer-z-t.github.io"
author: Zach Caterer

sass:
  sass_dir: assets/css
  style: :compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - _data

permalink: /:year/:month/:day/:title.html
